# Generated by Django 5.2.1 on 2025-05-27 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthDataUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="health_exports/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(db_index=True, max_length=100)),
                ("duration", models.FloatField()),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField()),
                ("creation_date", models.DateTimeField()),
                ("avg_heart_rate", models.FloatField(blank=True, null=True)),
                ("trimp_score", models.FloatField(blank=True, null=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="healthanalytics.healthdataupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("steps", models.IntegerField(blank=True, null=True)),
                ("steps_7day_avg", models.FloatField(blank=True, null=True)),
                ("step_streak", models.IntegerField(blank=True, null=True)),
                ("resting_hr", models.FloatField(blank=True, null=True)),
                ("basal_energy_kcal", models.FloatField(blank=True, null=True)),
                ("active_energy_kcal", models.FloatField(blank=True, null=True)),
                ("total_energy_kcal", models.FloatField(blank=True, null=True)),
                ("hrv_sdnn", models.FloatField(blank=True, null=True)),
                ("hrv_baseline", models.FloatField(blank=True, null=True)),
                ("hrv_z_score", models.FloatField(blank=True, null=True)),
                ("vo2_max", models.FloatField(blank=True, null=True)),
                ("met_minutes", models.FloatField(blank=True, null=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="healthanalytics.healthdataupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("upload", "date")},
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(db_index=True, max_length=100)),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField()),
                ("creation_date", models.DateTimeField()),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="healthanalytics.healthdataupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["type", "start_date"],
                        name="healthanaly_type_83f91b_idx",
                    ),
                    models.Index(
                        fields=["upload", "type"], name="healthanaly_upload__6d259f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NightlyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("respiratory_rate_mean", models.FloatField(blank=True, null=True)),
                ("respiratory_rate_baseline", models.FloatField(blank=True, null=True)),
                ("respiratory_rate_z_score", models.FloatField(blank=True, null=True)),
                ("respiratory_rate_elevated", models.BooleanField(default=False)),
                ("spo2_median", models.FloatField(blank=True, null=True)),
                ("spo2_p01", models.FloatField(blank=True, null=True)),
                ("pct_time_below_90", models.FloatField(blank=True, null=True)),
                ("wrist_temp", models.FloatField(blank=True, null=True)),
                ("temp_baseline", models.FloatField(blank=True, null=True)),
                ("temp_deviation", models.FloatField(blank=True, null=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nightly_metrics",
                        to="healthanalytics.healthdataupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("upload", "date")},
            },
        ),
    ]
